version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
      
  django:
    build: .
    container_name: django
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:5000
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    
  celery:
    build: .
    container_name: celery
    restart: always
    working_dir: /app
    command: celery -A picasso.celery worker --beat -l INFO
    depends_on:
      - redis
      - db
      - django
    env_file:
      - ./.env

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data


volumes:
  redis:

